### ISSUE TITLE
[BUG] Marker Scaling for Non-Square Tokens

### ISSUE THREAD

**Issue by arbron** [kckaiwei/TurnMarker-alt#35] opened 2021-01-21 07:02 UTC
When the turn marker is applied to rectangular tokens it scales into an awkward oval that wobbles as it rotates. The starting marker is also scaled oddly if it is enabled.

<img width="600" alt="Oval Marker" src="https://user-images.githubusercontent.com/19979839/105313554-cab21580-5b72-11eb-9b2d-1225c3c44ac2.png">

#### Versions
Foundry VTT: 0.7.9
Turn Marker: 2.7.3

#### To Recreate
1. Set the Width or Height for a token's image to be different values
2. Enable that marker's turn in combat

#### My Suggestion
It would be nice if the turn marker remained a circle no matter the dimensions of the token, with a diameter of either the shortest or longest edge of the token (maybe configurable in options, but probably just whichever looks nicest when tested).

**Comment by kckaiwei** [comment] 2021-01-21 13:45
Got it, yeah I can reproduce it. It's current size is calculated from the width/height, and I agree it's probably better to use width/or height only in these instances, or maybe some inbetween.

Haven't actually used tokens in this way, so never noticed, but should be an easy fix. Hardest part is probably deciding how to determine which size to use, lol.

**Comment by kckaiwei** [comment] 2021-01-22 19:59
@arbron 

![image](https://user-images.githubusercontent.com/12780629/105538836-027ba300-5cc2-11eb-9725-378f9f9d915a.png)


I have a fix in the pipe for 2.7.4, opted for the shorter side, so ratio = 1 doesn't stick out of the token rectangle. Since you can always adjust ratio as a setting, also since smaller looks better than larger by a large margin, imo :). Start markers will also scale accordingly as shown, and will be centered regardless of the grid, so it's center where the token used to be.

In the example, the token's been moved up 2 units.

I'll close this ticket when it's released.

**Closed** 2021-05-01 21:27 UTC
Labels: bug
